export const ErrorCode = {
  COMPANY_UNREACHABLE: "COMPANY_UNREACHABLE",
  NO_HIRING_PAGE: "NO_HIRING_PAGE",
  NO_DISCUSSION: "NO_DISCUSSION",
  JD_TOO_THIN: "JD_TOO_THIN",
  LLM_INVALID_JSON: "LLM_INVALID_JSON",
  RATE_LIMITED: "RATE_LIMITED",
  SCHEMA_INVALID: "SCHEMA_INVALID",
  PIPELINE_TIMEOUT: "PIPELINE_TIMEOUT",
  BATCH_TIMEOUT: "BATCH_TIMEOUT",
  VALIDATION: "VALIDATION",
  AUTH: "AUTH",
  DEDUPED: "DEDUPED",
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
